site_name: LangGraph Project Docs
site_description: Documentation for the LangGraph repository
repo_url: https://github.com/dineshpabbi10/research_agent
nav:
  - Home: index.md
  - Skills: skills.md
  - Vision: long_term_vision.md
theme:
  name: material
plugins:
  - search
