[tool.poetry]
name = "research-agent"
version = "0.1.0"
description = ""
authors = ["Dinesh Pabbi <dineshpabbi10@gmail.com>"]
readme = "README.md"
packages = [{include = "research_agent"}]

[tool.poetry.dependencies]
python = "^3.12"
langgraph = "^1.0.8"
langchain-openai = "^1.1.9"
langgraph-checkpoint-sqlite = "^3.0.3"
langchain-community = "^0.4.1"
pydantic-settings = "^2.13.0"
asyncio = "^4.0.0"


[tool.poetry.group.dev.dependencies]
mkdocs = "^1.6.1"
mkdocs-material = "^9.7.1"
pymdown-extensions = "^10.21"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
